### ISSUE TITLE
Migrate Key/Certs/passwords fields to Secret resources

### ISSUE THREAD

**Issue by bouskaJ** [securesign/secure-sign-operator#1]
There is bunch of fields in the `Securesign` API definition that are potentially secure sensitive and should be migrated to the Secret resource
```
	FulcioPublicKey  string `json:"fulcioPublicKey,omitempty"`
	FulcioPrivateKey string `json:"fulcioPrivateKey,omitempty"`
	FulcioCert       string `json:"fulcioCert,omitempty"`
	FulcioPassword   string `json:"fulcioPassword,omitempty"`
	RekorPrivateKey  string `json:"rekorPrivateKey,omitempty"`
```

**Comment by osmman** [comment]
I think that we should use [corev1.SecretKeySelector](https://pkg.go.dev/k8s.io/api/core/v1#SecretKeySelector) to reference secret resources. At least we should do that for private keys and passwords
