### ISSUE TITLE
[SECURESIGN-595] Operator upgrade support

### ISSUE THREAD

**Issue by bouskaJ** [securesign/secure-sign-operator#178]
When the new operator is upgraded, we need to upgrade installed resources (mainly deployments and pods). That means reset the platform and recreate.

**Comment by cooktheryan** [comment]
@bouskaJ is there anyway we could utilize the CreateOrUpdate functionality operator-sdk should provide https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#CreateOrUpdate

Here is how we used it in the past with Volsync https://github.com/backube/volsync/blob/main/controllers/mover/syncthing/mover.go#L398

**Comment by bouskaJ** [comment]
Hey, I did not know about that :+1: we solve resource update by https://github.com/securesign/secure-sign-operator/blob/main/controllers/common/action/base_action.go#L100 right now. The scenario of this issue is redeployment of the whole operator (to new release). I believe that everything should work after https://github.com/securesign/secure-sign-operator/issues/177 will be done but this is critical and we should dedicate some time, exercise it a little and cover this by test.
