### ISSUE TITLE
Allow for bring your own database 

### ISSUE THREAD

**Issue by cooktheryan** [securesign/secure-sign-operator#18]
If variables are set then we should not create a db and should connect to an existing

**Comment by bouskaJ** [comment]
The built-in database is automatically initialized with https://github.com/securesign/trillian/blob/redhat-v1.5/Dockerfile.database#L8. For the provided database we need to create schema with similar code https://github.com/sigstore/scaffolding/blob/main/cmd/trillian/createdb/main.go

**Comment by cooktheryan** [comment]
Pr #28

**Comment by cooktheryan** [comment]
closed by #30
