### ISSUE TITLE
Enable CTLog custom key injection

### ISSUE THREAD

**Issue by bouskaJ** [securesign/secure-sign-operator#33]
The CTLog component currently generate the private key on it's own. We should provide way on how to inject the customer generated key.

https://github.com/google/certificate-transparency-go/blob/master/trillian/docs/ManualDeployment.md#key-generation

**Comment by bouskaJ** [comment]
As discussed I will reopen this issue for fix

- There is hardcoded password that needs to be updated https://github.com/securesign/secure-sign-operator/blob/main/controllers/ctlog/utils/ctlog_config.go#L304
- Key type is hardcoded https://github.com/securesign/secure-sign-operator/blob/main/controllers/ctlog/utils/ctlog_config.go#L300 (The private key must either be for elliptic curves using NIST P-256 (as shown here), or for RSA signatures with SHA-256 and a 2048 bit (or larger) key (RFC 6962 s2.1.4).
- The API is not unified. In the CTlogCert, we have SecretName and SecretKey in other components like Fulcio or Rekor, we have only SecretName

**Comment by JasonPowr** [comment]
@bouskaJ with the key type, when its generated should it generate a ecdsa by default or should there be a choice between rsa and ecdsa through the api?

**Comment by bouskaJ** [comment]
> @bouskaJ with the key type, when its generated should it generate a ecdsa key by default or should there be a choice between rsa and ecdsa through the api?

I think we can follow the `scaffolding` and autogenerate `ecdsa`
