### ISSUE TITLE
[SECURESIGN-578] CR Status handling

### ISSUE THREAD

**Issue by bouskaJ** [securesign/secure-sign-operator#34]
Currently, we use the `phase` field on each CR. In case of error, there is no message on why it happened. 
We should take advantage from using [conditions](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions)

Also status on the `securesign` resource is not implemented yet.

**Comment by bouskaJ** [comment]
@osmman you mentioned that you played with `conditions`do you have any progress? May I assign this issue to you?

**Comment by osmman** [comment]
> @osmman you mentioned that you played with `conditions`do you have any progress? May I assign this issue to you?

Yes I can take it. Currently I am playing with TUF controller and auto discovering of public keys and certs for it. Currently I am putting status of is and one condition per service (Fulcio, Rekor, CTlog, TSA)
