### ISSUE TITLE
Global or namespaced operator

### ISSUE THREAD

**Issue by bouskaJ** [securesign/secure-sign-operator#4]
The current config create various projects on the cluster and deploy the securesign project in cluster-wide manner. This could be considered as the global operator installation. We should consider to modify operator for the namespaced deployment - keep the whole app in one namespace. This option brings option to create multiple securesign instances on single cluster.

**Comment by bouskaJ** [comment]
Also because of the multiple namespaces kind of deployment, we are unable to properly use owner references and the cluster can't handle cleanup by its own.
See https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/

**Comment by bouskaJ** [comment]
We can configure resources to keep PVCs and everything else if we want so. The problem with the multiple namespaces architecture is that if one thing fail, your cluster can become messy and it's hard to understand where the leftovers are and how to delete them. Working in single namespace you have great insight on what is the status of all components. To sum it up I see following benefits:

- great awareness about status of each component
- easier to delete/redeploy
- **easier RBAC policy** - only single SA is needed for the whole deployment
- multiple instances on single cluster
- easier operator code (this is last but not least - the namespaced operator follows the best practise for operator development. We can hit multiple problems in near future with multi-namespaced architecture).

I can't see any particular reason to break single TSA deployment into multiple namespaces.

**Comment by cooktheryan** [comment]
@bouskaJ I 100% agree with you. I was honestly just trying to follow the helm deployment. I think we are safe to do create a unique NS.

**Comment by lance** [comment]
Our aim with RHTAS is to provide an easy-to-use, easy-to-update, opinionated deployment for Sigstore on OpenShift (and eventually RHEL/Podman). Keeping everything in one namespace not only follows best practices for operator deployments, it also helps address problems with cleanup and enables multiple installations per cluster. I think this could be a somewhat substantial change to our charts, however, and shouldn't be done without holistic consideration of the entire stack. But, IMO it does make sense.

**Comment by sallyom** [comment]
I agree with @lance - we haven't considered this only because we've been following the patterns of the upstream helm charts, but it makes sense to explore this now with the operator.

**Comment by bouskaJ** [comment]
Thank you all for your comments.
