### ISSUE TITLE
Convention for referencing secrets in CRDs

### ISSUE THREAD

**Issue by osmman** [securesign/secure-sign-operator#55]
Currently every resource handling references to secret differently. We should standardise it into single method which is compatible with Kubernetes API conventions ([Naming](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-of-the-reference-field), [Examples](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#object-references-examples)). 

- [x]  Fulcio
- [x]  Rekor
- [x] Trillian
- [x] TUF
- [x] CTlog

**Comment by osmman** [comment]
Simple resource reference like this should work for us:
```
secretRef:
    name: ctlog-secret
    key: private
```

**Comment by osmman** [comment]
There is still ctlog, fulcio and trillian resources which need to be modified

**Comment by cooktheryan** [comment]
Apologies let me know if I can help on this
