### ISSUE TITLE
Define CRD structure

### ISSUE THREAD

**Issue by bouskaJ** [securesign/secure-sign-operator#6]
Right now, we have kind of hybrid CRD structure. You have two options how to deploy:

1) You can create [securesign](https://github.com/securesign/secure-sign-operator/blob/main/api/v1alpha1/securesign_types.go) resource with configuration for all components. This configuration is then automatically parsed and resources of kind [fulcio](https://github.com/securesign/secure-sign-operator/blob/main/api/v1alpha1/fulcio_types.go), [rekor](https://github.com/securesign/secure-sign-operator/blob/main/api/v1alpha1/rekor_types.go), [trillian](https://github.com/securesign/secure-sign-operator/blob/main/api/v1alpha1/trillian_types.go), [tuf](https://github.com/securesign/secure-sign-operator/blob/main/api/v1alpha1/tuf_types.go) and [ctlog](https://github.com/securesign/secure-sign-operator/blob/main/api/v1alpha1/ctlog_types.go) are created. Those specific resources holds the status of each component.

2) You can skip the [securesign](https://github.com/securesign/secure-sign-operator/blob/main/api/v1alpha1/securesign_types.go) resource and go directly with fulcio,rekor,trillian,tuf,ctlog resources.

Q: Do we want to keep this structure? We can rework it to keep everything in the `securesign` resource and remove the component specific resources (that could be really messy) OR remove the `securesign` resource and use method nr.2 as described above.

**Comment by osmman** [comment]
I think that 1. option will be nice to have because it will enable to have a simple default installation of whole stack. But I do not know if this is some antipattern to compose CRDs. 

I like to have specific resources which enables a loosely coupled system. Currently I see the benefit that components can be deployed into different namespaces.

**Comment by cooktheryan** [comment]
I agree with @osmman I love the idea of option 1 with an incredibly simple way to deploy the full stack. I do feel like there will be cases in the future where customers may only want to install a few of the components.

**Comment by cooktheryan** [comment]
@thefoxatwork any thoughts?

**Comment by TheFoxAtWork** [comment]
**Option 1**
+1 to @cooktheryan and @osmman 

It does not appear to be an anti-pattern. Further, there **are** occasions where customers may not want to deploy all the components and could have developed their own alternative that meets their unique needs.

**Comment by lance** [comment]
I agree with the sentiment here that option 1) is the correct path forward.
