### ISSUE TITLE
[SECURESIGN-570] Rekor add options to set trillian_log_server 

### ISSUE THREAD

**Issue by osmman** [securesign/secure-sign-operator#79]
We should add options to configure external trillian log server. Currently deployed Rekor instance is configured to use only Trillain instance in same namespace.

It should help https://github.com/securesign/secure-sign-operator/issues/38 issue.

**Comment by tommyd450** [comment]
Still figuring out operators so I will give this one a try. Unless someone is already working on it.

**Comment by bouskaJ** [comment]
Migrated to Jira
