### ISSUE TITLE
CLI tools onboarding

### ISSUE THREAD

**Issue by bouskaJ** [securesign/secure-sign-operator#9]
There is the client server present as part of the HELM installation (https://github.com/securesign/sigstore-ocp/blob/main/charts/trusted-artifact-signer/templates/clientserver-deployment.yaml). We should add this functionality to the operator too. Ensure that the the ConsoleCliDownloads for [rekor](https://github.com/securesign/sigstore-ocp/blob/main/charts/trusted-artifact-signer/templates/consoleclidownload-rekor.yaml), [cosign](https://github.com/securesign/sigstore-ocp/blob/main/charts/trusted-artifact-signer/templates/consoleclidownload-cosign.yaml) and [gitsign](https://github.com/securesign/sigstore-ocp/blob/main/charts/trusted-artifact-signer/templates/consoleclidownload-gitsign.yaml) are created.

**Comment by cooktheryan** [comment]
+1

**Comment by JasonPowr** [comment]
@lance is there an update for this? Does this work need to be done?

**Comment by cooktheryan** [comment]
@tommyd450 could you provide the latest snapshot images

**Comment by lance** [comment]
@JasonPowr sorry - I should have updated sooner. The Konflux team will not have binary distribution ready by TP2, so this should be done.
